version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles-telegram-files_server_1
      APP_PORT: 80

  server:
    image: ghcr.io/jarvis2f/telegram-files:latest
    init: true
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      # Umbrel provides APP_DATA_DIR; map it to the app's APP_ROOT
      APP_ROOT: /app/data
      # Optional: run as specific UID/GID if needed
      PUID: "1000"
      PGID: "1000"
      # Required: obtain from https://my.telegram.org/apps
      # Defaults help the app start on first install; replace in Umbrel app settings, then restart
      TELEGRAM_API_ID: ${TELEGRAM_API_ID:-1}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH:-placeholder}
      # NGINX port inside container is 80; app_proxy forwards traffic
      NGINX_PORT: 80
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/api/health"]
      interval: 20s
      retries: 10
      timeout: 10s
      start_period: 60s
