version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles-telegram-files_server_1
      APP_PORT: 80

  server:
    image: ghcr.io/jarvis2f/telegram-files:latest
    user: "1000:1000"
    init: true
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      # Umbrel provides APP_DATA_DIR; map it to the app's APP_ROOT
      APP_ROOT: /app/data
      # Required: obtain from https://my.telegram.org/apps (set via Umbrel env editor)
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      # NGINX port inside container is 80; app_proxy forwards traffic
      NGINX_PORT: 80
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/api/health"]
      interval: 10s
      retries: 3
      timeout: 10s
      start_period: 10s
version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles-hello-world_server_1
      APP_PORT: 3000
    
  server:
    image: getumbrel/community-app-store-hello-world:latest
    user: "1000:1000"
    init: true
